### Feature Sale - GET ALL / GET ONE (público, sin token)
@baseUrl = http://localhost:3002
@id = 1

# @name getAllSalesPublic
GET {{baseUrl}}/api/ventas

###

# @name getOneSalePublic
GET {{baseUrl}}/api/ventas/{{id}}
